import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowUpDown, ChevronLeft, ChevronRight, Filter, Plus, Search } from "lucide-react";
import { Link } from "react-router-dom";
import { EmptyState, ErrorState, LoadingState } from "../components/common/Feedback";
import { StatusBadge } from "../components/common/StatusBadge";
import { useAuth } from "../features/auth/AuthContext";
import { getWorkOrders } from "../services/workOrderApi";

export function WorkOrdersPage() {
  const { token } = useAuth(); const [page, setPage] = useState(0); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [priority, setPriority] = useState("");
  const query = useQuery({ queryKey: ["work-orders", page, search, status, priority], queryFn: () => getWorkOrders({ page, size: 20, search, status, priority }, token!), enabled: Boolean(token), placeholderData: (previous) => previous });
  const data = query.data;
  return <div className="page"><div className="page-heading"><div><p className="eyebrow">OPERATIONS</p><h1>Work Orders</h1><p>Search and manage work orders from the API.</p></div><Link className="primary-button" to="/work-orders/new"><Plus size={18} />Create Work Order</Link></div><section className="filter-bar"><div className="search-box"><Search size={18} /><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(0); }} placeholder="Search work orders..." aria-label="Search work orders" /></div><label><Filter size={16} /><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(0); }}><option value="">Filter by status</option><option value="NEW">NEW</option><option value="ASSIGNED">ASSIGNED</option><option value="IN_PROGRESS">IN PROGRESS</option><option value="ON_HOLD">ON HOLD</option><option value="COMPLETED">COMPLETED</option></select></label><label><select value={priority} onChange={(e) => { setPriority(e.target.value); setPage(0); }}><option value="">Filter by priority</option><option value="LOW">LOW</option><option value="MEDIUM">MEDIUM</option><option value="HIGH">HIGH</option><option value="CRITICAL">CRITICAL</option></select></label></section>
    <section className="table-card">{query.isLoading ? <LoadingState label="Loading work orders..." /> : query.isError ? <ErrorState message="Unable to load work orders. Please try again." /> : !data?.content.length ? <EmptyState message="No work orders available." /> : <><div className="data-table"><div className="table-row table-header"><span>Work order</span><span>Status</span><span>Priority</span><span>Customer</span><span>SLA</span></div>{data.content.map((workOrder) => <Link to={`/work-orders/${workOrder.id}`} className="table-row" key={workOrder.id}><span><strong>{workOrder.code}</strong><small>{workOrder.title}</small></span><span><StatusBadge status={workOrder.status} /></span><span><span className="priority">{workOrder.priority}</span></span><span>{workOrder.customerId || "Customer Name"}</span><span>{workOrder.slaDueDate || "SLA due date"}</span></Link>)}</div><div className="table-footer"><span>Page {(data.page ?? page) + 1} of {data.totalPages || 1}</span><div><button className="icon-button" onClick={() => setPage(Math.max(0, page - 1))} disabled={page === 0} aria-label="Previous page"><ChevronLeft /></button><button className="icon-button" onClick={() => setPage(page + 1)} disabled={page + 1 >= data.totalPages} aria-label="Next page"><ChevronRight /></button></div></div></>}</section></div>;
}
