spring.application.name=keystone-backend

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://127.0.0.1:5432/keystone}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Keystone@2026Strong!}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true

# JWT
jwt.secret=${JWT_SECRET:KEYSTONE-development-secret-key-change-this-before-production-123456789}