spring.application.name=keystone-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/keystone
spring.datasource.username=postgres
spring.datasource.password=Keystone@2026Strong!

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
